// Generates internal/tagger/*.gen.go from the JSON dumped by dump-model.mjs.
import { readFileSync, writeFileSync } from 'node:fs'

const DATA = new URL('../internal/tagger/modeldata/', import.meta.url)
const OUT = new URL('../internal/tagger/', import.meta.url)
const read = name => JSON.parse(readFileSync(new URL(name, DATA), 'utf8'))

const lexicon = read('lexicon.json')
const tagSet = read('tagset.json')
const matches = read('matches.json')
const misc = read('misc.json')
const hooks = read('hooks.json')

const header = `// Code generated by tools/gen-go.mjs. DO NOT EDIT.
// Source: compromise ${misc.version} (node_modules/compromise), dumped by tools/dump-model.mjs.

package tagger
`

// Patterns RE2 cannot express. Each maps to a Go predicate implemented by hand;
// the generator refuses to emit a pattern that is neither RE2-valid nor listed here.
const PREDICATES = {
  '^[\\p{Emoji_Presentation}\\p{Extended_Pictographic}]': 'pictographic',
}

// Translates a JS regex source into Go regexp syntax.
//
// Only the escape spelling changes: \uXXXX becomes \x{XXXX}, which is the same
// codepoint. Backslash runs are walked pairwise so an escaped backslash stays an
// escaped backslash — compromise's 'un-vite' rule is `\\-`, a literal backslash
// followed by a hyphen, and collapsing it to `\-` would make the rule fire on
// ordinary hyphenated words the TS oracle never tagged.
const goPattern = function (src, flags) {
  let out = ''
  for (let i = 0; i < src.length; ) {
    const ch = src[i]
    if (ch === '\\') {
      const next = src[i + 1]
      if (next === 'u' && /^[0-9a-fA-F]{4}$/.test(src.slice(i + 2, i + 6))) {
        out += '\\x{' + src.slice(i + 2, i + 6).toLowerCase() + '}'
        i += 6
        continue
      }
      // any other escape, including \\, is copied as a unit so its meaning holds
      out += ch + (next === undefined ? '' : next)
      i += next === undefined ? 1 : 2
      continue
    }
    const cp = ch.codePointAt(0)
    if (cp > 0x7e) {
      out += '\\x{' + cp.toString(16) + '}'
      i += ch.length
      continue
    }
    out += ch
    i += 1
  }
  return flags && flags.includes('i') ? '(?i)' + out : out
}

const re2Failures = []
const emittedPatterns = []

// Verifies a pattern against Go's regexp at generation time. Node cannot run Go's
// parser, so this approximates it by rejecting the constructs RE2 lacks.
const checkRE2 = function (pattern, where) {
  const unsupported = [
    [/\(\?[=!]/, 'lookahead'],
    [/\(\?<[=!]/, 'lookbehind'],
    [/\\[1-9]/, 'backreference'],
    [/\\p\{Emoji_Presentation\}/, '\\p{Emoji_Presentation}'],
    [/\\p\{Extended_Pictographic\}/, '\\p{Extended_Pictographic}'],
  ]
  for (const [re, why] of unsupported) {
    if (re.test(pattern)) {
      re2Failures.push({ pattern, where, why })
      return false
    }
  }
  emittedPatterns.push({ pattern, where })
  return true
}

const tagsOf = tag => (tag === undefined || tag === null ? [] : Array.isArray(tag) ? tag : [tag])

const emitRegexRule = function (r) {
  const parts = []
  const pattern = goPattern(r.regex, r.flags)
  if (PREDICATES[r.regex] !== undefined) {
    parts.push(`predicate: ${q(PREDICATES[r.regex])}`)
  } else {
    checkRE2(pattern, `regexRule ${r.reason || r.regex}`)
    parts.push(`pattern: ${q(pattern)}`)
  }
  parts.push(`tags: []string{${strSlice(tagsOf(r.tag))}}`)
  parts.push(`reason: ${q(r.reason || '')}`)
  return `{${parts.join(', ')}}`
}

// Emits a Go string literal. Every non-ASCII rune is escaped, because Go's parser
// rejects a literal U+FEFF anywhere but the first bytes of a file, and the model
// data carries zero-width joiners and other invisibles that must survive verbatim.
const q = function (s) {
  let out = '"'
  for (const ch of String(s)) {
    const cp = ch.codePointAt(0)
    if (ch === '"') out += '\\"'
    else if (ch === '\\') out += '\\\\'
    else if (ch === '\n') out += '\\n'
    else if (ch === '\t') out += '\\t'
    else if (ch === '\r') out += '\\r'
    else if (cp < 0x20 || cp === 0x7f) out += '\\x' + cp.toString(16).padStart(2, '0')
    else if (cp < 0x7f) out += ch
    else if (cp <= 0xffff) out += '\\u' + cp.toString(16).padStart(4, '0')
    else out += '\\U' + cp.toString(16).padStart(8, '0')
  }
  return out + '"'
}

// A null clue value is falsy in compromise, so the lookup falls through to the
// next clue source. Emitting it as the string "null" would instead make it a
// winning tag named 'null'.
const strMap = obj => {
  const keys = Object.keys(obj)
    .filter(k => obj[k] !== null && obj[k] !== undefined)
    .sort()
  return keys.map(k => `\t${q(k)}: ${q(String(obj[k]))},`).join('\n')
}

const boolSet = obj => {
  const keys = Object.keys(obj)
    .filter(k => obj[k] === true)
    .sort()
  return keys.map(k => `\t${q(k)}: {},`).join('\n')
}

const strSlice = arr => arr.map(q).join(', ')

// --- lexicon.gen.go ---
{
  // lexicon values are either a tag string or an array of tags
  const single = {}
  const multi = {}
  for (const [word, tag] of Object.entries(lexicon)) {
    if (Array.isArray(tag)) multi[word] = tag
    else single[word] = tag
  }
  const lines = [header]
  lines.push(`// lexicon holds ${Object.keys(lexicon).length} word->tag entries.`)
  lines.push(`var lexicon = map[string]string{`)
  lines.push(strMap(single))
  lines.push(`}\n`)
  lines.push(`var lexiconMulti = map[string][]string{`)
  for (const k of Object.keys(multi).sort()) {
    lines.push(`\t${q(k)}: {${strSlice(multi[k])}},`)
  }
  lines.push(`}\n`)
  lines.push(`var multiCache = map[string]int{`)
  for (const k of Object.keys(misc.multiCache).sort()) {
    lines.push(`\t${q(k)}: ${misc.multiCache[k]},`)
  }
  lines.push(`}\n`)
  lines.push(`var frozenLex = map[string]string{`)
  lines.push(strMap(misc.frozenLex))
  lines.push(`}\n`)
  writeFileSync(new URL('lexicon.gen.go', OUT), lines.join('\n'))
}

// --- tagset.gen.go ---
{
  const lines = [header]
  lines.push(`type tagInfo struct {`)
  lines.push(`\tnot      []string`)
  lines.push(`\tparents  []string`)
  lines.push(`\tchildren []string`)
  lines.push(`}\n`)
  lines.push(`var tagSet = map[string]tagInfo{`)
  for (const k of Object.keys(tagSet).sort()) {
    const t = tagSet[k]
    lines.push(
      `\t${q(k)}: {not: []string{${strSlice(t.not)}}, parents: []string{${strSlice(
        t.parents,
      )}}, children: []string{${strSlice(t.children)}}},`,
    )
  }
  lines.push(`}\n`)
  writeFileSync(new URL('tagset.gen.go', OUT), lines.join('\n'))
}

// --- suffix.gen.go ---
{
  const lines = []
  const bucketed = (name, buckets) => {
    lines.push(`var ${name} = []map[string]string{`)
    for (const bucket of buckets) {
      if (!bucket || Object.keys(bucket).length === 0) {
        lines.push(`\tnil,`)
        continue
      }
      lines.push(`\t{`)
      for (const k of Object.keys(bucket).sort()) {
        lines.push(`\t\t${q(k)}: ${q(bucket[k])},`)
      }
      lines.push(`\t},`)
    }
    lines.push(`}\n`)
  }
  bucketed('suffixPatterns', misc.suffixPatterns)
  bucketed('prefixPatterns', misc.prefixPatterns)

  const regexList = (name, list) => {
    lines.push(`var ${name} = []regexRule{`)
    for (const r of list) {
      lines.push(`\t${emitRegexRule(r)},`)
    }
    lines.push(`}\n`)
  }
  lines.push(`type regexRule struct {`)
  lines.push(`\tpattern string`)
  lines.push(`\ttags    []string`)
  lines.push(`\treason  string`)
  // A rule whose pattern RE2 cannot express is matched by a named Go predicate
  // instead; see pictographic in tagger.go.
  lines.push(`\tpredicate string`)
  lines.push(`\tre      *regexp.Regexp`)
  lines.push(`}\n`)
  regexList('regexText', misc.regexText)
  regexList('regexNormal', misc.regexNormal)
  regexList('regexNumbers', misc.regexNumbers)

  lines.push(`var endsWith = map[string][]regexRule{`)
  for (const k of Object.keys(misc.endsWith).sort()) {
    lines.push(`\t${q(k)}: {`)
    for (const r of misc.endsWith[k]) {
      lines.push(`\t\t${emitRegexRule(r)},`)
    }
    lines.push(`\t},`)
  }
  lines.push(`}\n`)

  lines.push(`var switches = map[string]string{`)
  lines.push(strMap(misc.switches))
  lines.push(`}\n`)

  lines.push(`type clueSet struct {`)
  lines.push(`\tbeforeTags  map[string]string`)
  lines.push(`\tafterTags   map[string]string`)
  lines.push(`\tbeforeWords map[string]string`)
  lines.push(`\tafterWords  map[string]string`)
  lines.push(`}\n`)
  lines.push(`var clues = map[string]clueSet{`)
  for (const form of Object.keys(misc.clues).sort()) {
    const c = misc.clues[form]
    const sub = key => {
      const o = c[key] || {}
      if (Object.keys(o).length === 0) return 'nil'
      return `map[string]string{\n${strMap(o)
        .split('\n')
        .map(l => '\t\t' + l)
        .join('\n')}\n\t\t}`
    }
    lines.push(`\t${q(form)}: {`)
    lines.push(`\t\tbeforeTags: ${sub('beforeTags')},`)
    lines.push(`\t\tafterTags: ${sub('afterTags')},`)
    lines.push(`\t\tbeforeWords: ${sub('beforeWords')},`)
    lines.push(`\t\tafterWords: ${sub('afterWords')},`)
    lines.push(`\t},`)
  }
  lines.push(`}\n`)

  const pairList = (name, arr) => {
    lines.push(`var ${name} = [][2]string{`)
    for (const [a, b] of arr) lines.push(`\t{${q(a)}, ${q(b)}},`)
    lines.push(`}\n`)
  }
  pairList('neighbourLeftTags', misc.neighbours.leftTags)
  pairList('neighbourLeftWords', misc.neighbours.leftWords)
  pairList('neighbourRightTags', misc.neighbours.rightTags)
  pairList('neighbourRightWords', misc.neighbours.rightWords)

  const setOf = (name, obj) => {
    lines.push(`var ${name} = map[string]struct{}{`)
    lines.push(boolSet(obj))
    lines.push(`}\n`)
  }
  setOf('orgWords', misc.orgWords)
  setOf('placeWords', misc.placeWords)
  setOf('uncountable', misc.uncountable)
  setOf('abbreviations', misc.abbreviations)
  setOf('numberSuffixes', misc.numberSuffixes)
  setOf('prePunctuation', misc.prePunctuation)
  setOf('postPunctuation', misc.postPunctuation)

  lines.push(`var wordPrefixes = map[string]struct{}{`)
  lines.push(boolSet(misc.prefixes))
  lines.push(`}\n`)
  lines.push(`var wordSuffixes = map[string]struct{}{`)
  lines.push(boolSet(misc.suffixes))
  lines.push(`}\n`)

  lines.push(`var emoticons = map[string]struct{}{`)
  lines.push(boolSet(misc.emoticons))
  lines.push(`}\n`)

  lines.push(`var aliases = map[string]string{`)
  lines.push(strMap(misc.aliases))
  lines.push(`}\n`)

  lines.push(`var unicodeFold = map[string]string{`)
  lines.push(strMap(misc.unicode))
  lines.push(`}\n`)

  lines.push(`var irregularPlurals = map[string]string{`)
  lines.push(strMap(misc.irregularPlurals))
  lines.push(`}\n`)

  // suffix-substitution tables used by the verb/noun/adjective transforms
  lines.push(`type transformModel struct {`)
  lines.push(`\treversed bool`)
  lines.push(`\tfwd      map[string]string`)
  lines.push(`\tboth     map[string]string`)
  lines.push(`\trev      map[string]string`)
  lines.push(`\tex       map[string]string`)
  lines.push(`}\n`)
  lines.push(`var transformModels = map[string]transformModel{`)
  for (const name of Object.keys(misc.models).sort()) {
    const m = misc.models[name] || {}
    const sub = key => {
      const o = m[key] || {}
      if (Object.keys(o).length === 0) return 'nil'
      return `map[string]string{\n${strMap(o)
        .split('\n')
        .map(l => '\t\t' + l)
        .join('\n')}\n\t\t}`
    }
    lines.push(`\t${q(name)}: {`)
    lines.push(`\t\treversed: ${m.reversed === true},`)
    lines.push(`\t\tfwd: ${sub('fwd')},`)
    lines.push(`\t\tboth: ${sub('both')},`)
    lines.push(`\t\trev: ${sub('rev')},`)
    lines.push(`\t\tex: ${sub('ex')},`)
    lines.push(`\t},`)
  }
  lines.push(`}\n`)

  writeFileSync(new URL('suffix.gen.go', OUT), header + '\nimport "regexp"\n\n' + lines.join('\n'))
}

// --- matches.gen.go ---
{
  const lines = []

  const emitReg = (r, indent) => {
    const p = []
    if (r.word !== undefined) p.push(`word: ${q(r.word)}`)
    if (r.tag !== undefined) p.push(`tag: ${q(r.tag)}`)
    if (r.method !== undefined) p.push(`method: ${q(r.method)}`)
    if (r.switch !== undefined) p.push(`switchForm: ${q(r.switch)}`)
    if (r.regex !== undefined) {
      const pat = goPattern(r.regex, r.regexFlags)
      if (PREDICATES[r.regex] !== undefined) {
        p.push(`predicate: ${q(PREDICATES[r.regex])}`)
      } else {
        checkRE2(pat, `matchRule reg /${r.regex}/`)
        p.push(`pattern: ${q(pat)}`)
      }
    }
    if (r.anything) p.push(`anything: true`)
    if (r.start) p.push(`start: true`)
    if (r.end) p.push(`end: true`)
    if (r.negative) p.push(`negative: true`)
    if (r.optional) p.push(`optional: true`)
    if (r.greedy) p.push(`greedy: true`)
    if (r.min !== undefined) p.push(`min: ${r.min}, hasMin: true`)
    if (r.max !== undefined) p.push(`max: ${r.max}, hasMax: true`)
    if (r.group !== undefined && r.group !== null) p.push(`group: ${q(String(r.group))}`)
    if (r.groupStart) p.push(`groupStart: true`)
    if (r.groupEnd) p.push(`groupEnd: true`)
    if (r.operator !== undefined) p.push(`operator: ${q(r.operator)}`)
    if (r.fastOr !== undefined) {
      const items = r.fastOr.slice().sort()
      p.push(`fastOr: map[string]struct{}{${items.map(w => `${q(w)}: {}`).join(', ')}}`)
    }
    if (r.choices !== undefined) {
      const blocks = r.choices
        .map(block => `{${block.map(c => emitReg(c, indent + 1)).join(', ')}}`)
        .join(', ')
      p.push(`choices: [][]reg{${blocks}}`)
    }
    return `{${p.join(', ')}}`
  }

  lines.push(`type reg struct {`)
  lines.push(`\tword       string`)
  lines.push(`\ttag        string`)
  lines.push(`\tmethod     string`)
  lines.push(`\tswitchForm string`)
  lines.push(`\tpattern    string`)
  lines.push(`\tpredicate  string`)
  lines.push(`\tre         *regexp.Regexp`)
  lines.push(`\tanything   bool`)
  lines.push(`\tstart      bool`)
  lines.push(`\tend        bool`)
  lines.push(`\tnegative   bool`)
  lines.push(`\toptional   bool`)
  lines.push(`\tgreedy     bool`)
  lines.push(`\tmin        int`)
  lines.push(`\thasMin     bool`)
  lines.push(`\tmax        int`)
  lines.push(`\thasMax     bool`)
  lines.push(`\tgroup      string`)
  lines.push(`\tgroupStart bool`)
  lines.push(`\tgroupEnd   bool`)
  lines.push(`\toperator   string`)
  lines.push(`\tfastOr     map[string]struct{}`)
  lines.push(`\tchoices    [][]reg`)
  lines.push(`}\n`)

  lines.push(`type matchRule struct {`)
  lines.push(`\tmatch    string`)
  lines.push(`\ttags     []string`)
  lines.push(`\tunTag    []string`)
  lines.push(`\tgroup    string`)
  lines.push(`\thasGroup bool`)
  lines.push(`\treason   string`)
  lines.push(`\tifNo     []string`)
  lines.push(`\tregs     []reg`)
  lines.push(`\tnotIf    []reg`)
  lines.push(`\tneeds    []string`)
  lines.push(`\twants    []string`)
  lines.push(`\tminWant  int`)
  lines.push(`\tminWords int`)
  lines.push(`}\n`)

  lines.push(`var matchRules = []matchRule{`)
  for (const m of matches) {
    const tags = m.tag === undefined || m.tag === null ? [] : Array.isArray(m.tag) ? m.tag : [m.tag]
    const unTag = m.unTag === undefined || m.unTag === null ? [] : Array.isArray(m.unTag) ? m.unTag : [m.unTag]
    const ifNo = m.ifNo === undefined || m.ifNo === null ? [] : m.ifNo
    const parts = [
      `match: ${q(m.match)}`,
      `tags: []string{${strSlice(tags)}}`,
    ]
    if (unTag.length) parts.push(`unTag: []string{${strSlice(unTag)}}`)
    if (m.group !== null && m.group !== undefined) parts.push(`group: ${q(String(m.group))}, hasGroup: true`)
    parts.push(`reason: ${q(m.reason || '')}`)
    if (ifNo.length) parts.push(`ifNo: []string{${strSlice(ifNo)}}`)
    parts.push(`regs: []reg{${m.regs.map(r => emitReg(r, 0)).join(', ')}}`)
    if (m.notIf) parts.push(`notIf: []reg{${m.notIf.map(r => emitReg(r, 0)).join(', ')}}`)
    parts.push(`needs: []string{${strSlice(m.needs)}}`)
    parts.push(`wants: []string{${strSlice(m.wants)}}`)
    parts.push(`minWant: ${m.minWant}`)
    parts.push(`minWords: ${m.minWords}`)
    lines.push(`\t{${parts.join(', ')}},`)
  }
  lines.push(`}\n`)

  lines.push(`var contractions = []contraction{`)
  for (const c of misc.contractions) {
    const parts = []
    if (c.word !== undefined) parts.push(`word: ${q(c.word)}`)
    if (c.before !== undefined) parts.push(`before: ${q(c.before)}`)
    if (c.after !== undefined) parts.push(`after: ${q(c.after)}`)
    parts.push(`out: []string{${strSlice(c.out)}}`)
    lines.push(`\t{${parts.join(', ')}},`)
  }
  lines.push(`}\n`)

  // Rule application order is the hook-map order, not the rule-list order.
  lines.push(`type hookBucket struct {`)
  lines.push(`\tkey   string`)
  lines.push(`\trules []int`)
  lines.push(`}\n`)
  lines.push(`var hookOrder = []hookBucket{`)
  for (const b of hooks.hookOrder) {
    lines.push(`\t{key: ${q(b.key)}, rules: []int{${b.rules.join(', ')}}},`)
  }
  lines.push(`}\n`)
  lines.push(`var alwaysRules = []int{${hooks.always.join(', ')}}\n`)

  writeFileSync(new URL('matches.gen.go', OUT), header + '\nimport "regexp"\n\n' + lines.join('\n'))
}

// --- pictographic.gen.go ---
// The one pattern RE2 cannot express. The range table is derived from the same JS
// engine that produced the golden files, so the Go predicate agrees by construction.
{
  const rePict = /\p{Extended_Pictographic}/u
  const rePres = /\p{Emoji_Presentation}/u
  const ranges = []
  let start = -1
  let prevIn = false
  for (let cp = 0; cp <= 0x10ffff; cp++) {
    if (cp >= 0xd800 && cp <= 0xdfff) {
      if (prevIn) {
        ranges.push([start, cp - 1])
        prevIn = false
      }
      continue
    }
    const ch = String.fromCodePoint(cp)
    const isIn = rePict.test(ch) || rePres.test(ch)
    if (isIn && !prevIn) {
      start = cp
      prevIn = true
    } else if (!isIn && prevIn) {
      ranges.push([start, cp - 1])
      prevIn = false
    }
  }
  if (prevIn) ranges.push([start, 0x10ffff])

  const lines = []
  lines.push('import "unicode"\n')
  lines.push(`// pictographicTable is Extended_Pictographic + Emoji_Presentation, ${ranges.length} ranges.`)
  lines.push('var pictographicTable = &unicode.RangeTable{')
  const r16 = ranges.filter(([, hi]) => hi <= 0xffff)
  const r32 = ranges.filter(([, hi]) => hi > 0xffff)
  lines.push('\tR16: []unicode.Range16{')
  for (const [lo, hi] of r16) {
    lines.push(`\t\t{Lo: 0x${lo.toString(16)}, Hi: 0x${hi.toString(16)}, Stride: 1},`)
  }
  lines.push('\t},')
  lines.push('\tR32: []unicode.Range32{')
  for (const [lo, hi] of r32) {
    lines.push(`\t\t{Lo: 0x${lo.toString(16)}, Hi: 0x${hi.toString(16)}, Stride: 1},`)
  }
  lines.push('\t},')
  lines.push('}\n')
  writeFileSync(new URL('pictographic.gen.go', OUT), header + '\n' + lines.join('\n'))
}

// The regex checks above are a fast approximation; this compiles every emitted
// pattern with Go's own parser, so an init-time panic can never ship.
{
  const { execFileSync } = await import('node:child_process')
  try {
    execFileSync('go', ['run', './re2probe'], {
      cwd: new URL('.', import.meta.url).pathname,
      input: JSON.stringify(emittedPatterns),
      stdio: ['pipe', 'inherit', 'inherit'],
    })
    console.log(`verified ${emittedPatterns.length} patterns compile under Go's regexp`)
  } catch {
    throw new Error("the patterns listed above do not compile under Go's regexp")
  }
}

if (re2Failures.length > 0) {
  for (const f of re2Failures) {
    console.error(`RE2-incompatible (${f.why}) in ${f.where}: ${f.pattern}`)
  }
  throw new Error(
    `${re2Failures.length} pattern(s) cannot compile under Go's regexp. ` +
      `Add a predicate for each to PREDICATES and implement it in tagger.go.`,
  )
}

console.log('generated Go sources from compromise', misc.version)
